version: "3.7"
services:
  photo_server:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
      - type: bind
        source: ./test_pics
        target: /usr/src/pics